pipeline:
    stages:
        - stage:
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          namespace: <+input>
                          connectorRef: account.testK8sConnector1oEpaAcyE6
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    connectorRef: account.testDockerConnectorTz237jUOWL
                                    image: maven
                                    command: "commitSha1=<+codebase.commitSha>\r

                                        export commitSha1\r

                                        targetBranch1=<+codebase.targetBranch>\r

                                        export targetBranch1\r

                                        sourceBranch=<+codebase.sourceBranch>\r

                                        export sourceBranch1\r

                                        prNumber=<+codebase.prNumber>\r

                                        export prNumber\r

                                        prTitle=<+codebase.prTitle>\r

                                        export prTitle\r

                                        export commitRef=<+codebase.commitRef>\r

                                        echo <+codebase.repoUrl>\r

                                        echo <+codebase.gitUserId>\r

                                        echo <+codebase.gitUserEmail>\r

                                        echo <+codebase.gitUser>\r

                                        echo <+codebase.gitUserAvatar>\r

                                        echo <+codebase.pullRequestLink>\r

                                        echo <+codebase.pullRequestBody>\r

                                        echo <+codebase.state>"
                                    privileged: false
                                    outputVariables:
                                        - name: commitSha1
                                        - name: targetBranch1
                                        - name: sourceBranch1
                                        - name: prNumber
                                        - name: prTitle
                                name: run1
                                identifier: run1
                  cloneCodebase: true
              name: gitsync
              identifier: gitsync
    properties:
        ci:
            codebase:
                connectorRef: account.testGitConnectorVFfUKHUp3T
                build: <+input>
    projectIdentifier: GitSyncCI1
    orgIdentifier: default
    name: gitsync
    identifier: gitsync
