pipeline:
    name: gitsync
    identifier: gitsync
    projectIdentifier: GitSyncCI1
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: gitsync
              identifier: gitsync
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.testK8sConnectorvmIzIJziIq
                          namespace: <+input>
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: run1
                                identifier: run1
                                spec:
                                    connectorRef: account.testDockerConnectorTz237jUOWL
                                    image: maven
                                    command: "if <+codebase.commitSha> == \"cd7c274fdbb19d9d1a24ee11999d466127dc1e27\"\r

                                        then true\r

                                        fi"
                                    privileged: false
              variables: []
    properties:
        ci:
            codebase:
                connectorRef: account.testGitConnectorpIs0r99ZOR
                build: <+input>
