pipeline:
    name: gitsync
    identifier: gitsync
    projectIdentifier: GitSyncCI1
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: gitsync
              identifier: gitsync
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.testK8sConnector98SHbz9GXQ
                          namespace: <+input>
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: run1
                                identifier: run1
                                spec:
                                    connectorRef: account.testDockerConnectorTz237jUOWL
                                    image: maven
                                    command: echo test
                                    privileged: false
                          - step:
                                type: S3Upload
                                name: upload
                                identifier: upload
                                spec:
                                    connectorRef: <+input>
                                    region: <+input>
                                    bucket: <+input>
                                    sourcePath: <+input>
                          - step:
                                type: BuildAndPushGCR
                                name: asdasd
                                identifier: asdasd
                                spec:
                                    connectorRef: <+input>
                                    host: <+input>
                                    projectID: <+input>
                                    imageName: <+input>
                                    tags: <+input>
                                    buildArgs: <+input>
                                    optimize: true
              variables: []
    properties:
        ci:
            codebase:
                connectorRef: account.testGitConnectorp45c3PcMXu
                build: <+input>
