pipeline:
    stages:
        - stage:
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          namespace: <+input>
                          connectorRef: account.testK8sConnector1oEpaAcyE6
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    connectorRef: account.testDockerConnectorTz237jUOWL
                                    image: maven
                                    command: |-
                                        commitSha1=<+codebase.commitSha>
                                        export commitSha1
                                        targetBranch=<+codebase.targetBranch>
                                        export targetBranch
                                    privileged: false
                                name: run1
                                identifier: run1
                  cloneCodebase: true
              name: gitsync
              identifier: gitsync
              variables: []
    properties:
        ci:
            codebase:
                connectorRef: account.testGitConnectorVFfUKHUp3T
                build: <+input>
    projectIdentifier: GitSyncCI1
    orgIdentifier: default
    name: gitsync
    identifier: gitsync
