pipeline:
    stages:
        - stage:
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          namespace: <+input>
                          connectorRef: account.testK8sConnector1oEpaAcyE6
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    connectorRef: account.testDockerConnectorTz237jUOWL
                                    image: maven
                                    command: |-
                                        commitSha1=<+codebase.commitSha>
                                        export commitSha1
                                        targetBranch1=<+codebase.targetBranch>
                                        export targetBranch1
                                        sourceBranch=<+codebase.sourceBranch>
                                        export sourceBranch1
                                        prNumber=<+codebase.prNumber>
                                        export prNumber
                                        echo <+codebase.prTitle>
                                        echo <+codebase.commitRef>
                                        echo <+codebase.repoUrl>
                                        echo <+codebase.gitUserId>
                                        echo <+codebase.gitUserEmail>
                                        echo <+codebase.gitUser>
                                        echo <+codebase.gitUserAvatar>
                                        echo <+codebase.pullRequestLink>
                                        echo <+codebase.pullRequestBody>
                                        echo <+codebase.state>
                                    privileged: false
                                name: run1
                                identifier: run1
                  cloneCodebase: true
              name: gitsync
              identifier: gitsync
              variables: []
    properties:
        ci:
            codebase:
                connectorRef: account.testGitConnectorVFfUKHUp3T
                build: <+input>
    projectIdentifier: GitSyncCI1
    orgIdentifier: default
    name: gitsync
    identifier: gitsync
