pipeline:
    name: gitsync
    identifier: gitsync
    projectIdentifier: GitSyncCI1
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: gitsync
              identifier: gitsync
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.testK8sConnector1oEpaAcyE6
                          namespace: <+input>
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: run1
                                identifier: run1
                                spec:
                                    connectorRef: account.testDockerConnectorTz237jUOWL
                                    image: maven
                                    command: "commitSha=<+codebase.commitSha>\r

                                        export commitSha\r

                                        targetBranch=<+codebase.targetBranch>\r

                                        export targetBranch\r

                                        sourceBranch=<+codebase.sourceBranch>\r

                                        export sourceBranch\r

                                        prNumber=<+codebase.prNumber>\r

                                        export prNumber\r

                                        prTitle=<+codebase.prTitle>\r

                                        export prTitle\r

                                        export commitRef=<+codebase.commitRef>\r

                                        echo <+codebase.repoUrl>\r

                                        echo <+codebase.gitUserId>\r

                                        echo <+codebase.gitUserEmail>\r

                                        echo <+codebase.gitUser>\r

                                        echo <+codebase.gitUserAvatar>\r

                                        echo <+codebase.pullRequestLink>\r

                                        echo <+codebase.pullRequestBody>\r

                                        echo <+codebase.state>"
                                    privileged: false
                                    outputVariables:
                                        - name: commitSha
                                        - name: targetBranch
                                        - name: sourceBranch
                                        - name: prNumber
                                        - name: prTitle
              variables: []
    properties:
        ci:
            codebase:
                connectorRef: account.testGitConnectorVFfUKHUp3T
                build: <+input>
